#!/bin/bash
if [ -n "$1" ] && [ -n "$2" ] && [ -n "$3" ] && [ -n "$4" ]
then
	mydir=`dirname $0`
	if [ $1 = '1' ] 
	then 
		sh "$mydir/t5_1" $2 $3 $4
	elif [ $1 = '2' ] 
	then 
		sh "$mydir/t5_2" $2 $3 $4
	elif [ $1 = '3' ] 
	then 
		sh "$mydir/t5_3" $2 $3 $4
	fi
else
	echo Не указаны аргументы!
fi
